name: fsc_ibb
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^1.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^4.0.4
  google_fonts: ^2.3.1
  intl: ^0.17.0
  logger: ^0.9.2
  splashscreen: ^1.3.5
  stacked: ^1.7.6
  stacked_services: ^0.5.4+2
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true

